services:
  backend:
    image: ghcr.io/kory291/tt_reservations:latest
    networks:
      - net
    env_file: 
      - path: ./.backend.env
        required: true
    restart: unless-stopped


  frontend:
    image: "ghcr.io/kory291/tt_reservations_frontend:latest" 
    networks:
      - net
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-4200}:4200"
    env_file:
      - path: ./.frontend.env
        required: false


networks:
  net: