services:
  backend:
    image: ghcr.io/kory291/tt_reservations:latest
    networks:
      - net
    volumes:
      - .env:.env
    restart: unless-stopped


  frontend:
    image: "ghcr.io/kory291/tt_reservations_frontend:latest" 
    networks:
      - net
    restart: unless-stopped

networks:
  net: