services:
  backend:
    image: ghcr.io/kory291/tt_reservations:latest
    ports:
      - "${BACKEND_PORT:-3000}:8000"
    env_file: 
      - path: ./.backend.env
        required: true
    restart: unless-stopped


  frontend:
    image: "ghcr.io/kory291/tt_reservations_frontend:latest" 
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT:-4200}:4200"
    env_file:
      - path: ./.frontend.env
        required: false