name: Build TT_Reservations image

on:
  push:
    branches:
      - main
  

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build images
        run: |
          docker build -f tt_reservations/Dockerfile -t tt_reservations:latest .
          docker build -f tt-reservations-frontend/Dockerfile -t tt_reservations_frontend:latest .

      - name: Push images
        run: |
          docker login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }}
          docker tag tt_reservations:latest ghcr.io/kory291/tt_reservations:latest
          docker tag tt_reservations_frontend:latest ghcr.io/kory291/tt_reservations_frontend:latest
          docker push ghcr.io/kory291/tt_reservations:latest
          docker push ghcr.io/kory291/tt_reservations_frontend:latest
    permissions:
      contents: read
      packages: write
      id-token: write